# Generated by Django 4.2.6 on 2023-10-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_comment_options_alter_comment_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="posted_by",
            field=models.CharField(default="dsfs", max_length=100),
            preserve_default=False,
        ),
    ]
